const tools=[
['📄','JPG → PDF','Image/PDF','jpgpdf','एक या कई images को PDF में बदलें'],['🖼️','PDF → JPG','PDF','pdfjpg','PDF pages को JPG में बदलें'],['🔄','JPG → PNG','Image','jpgpng','JPG को PNG में बदलें'],['🔄','PNG → JPG','Image','pngjpg','PNG को JPG में बदलें'],['🗜️','Image Compressor','Image','compress','Image size कम करें'],['📐','Image Resizer','Image','resize','Width और height बदलें'],['📚','Merge PDF','PDF','merge','कई PDF को एक में जोड़ें'],['✂️','Split PDF','PDF','split','चुने हुए PDF pages निकालें'],['🗜️','Compress PDF','PDF','pdfcompress','PDF को browser में re-save/optimize करें'],['🔢','Word Counter','Text','words','Words और characters गिनें'],['Aa','Case Converter','Text','case','UPPER/lower/Title/Sentence'],['％','Percentage Calculator','Calculator','percent','Percentage निकालें'],['🎂','Age Calculator','Calculator','age','जन्मतिथि से उम्र'],['💰','EMI Calculator','Calculator','emi','EMI, interest और total'],['🧾','GST Calculator','Calculator','gst','GST add/remove'],['🏷️','Discount Calculator','Calculator','discount','Discount और final price'],['⚖️','BMI Calculator','Calculator','bmi','BMI निकालें'],['📅','Date Calculator','Utility','date','Dates का अंतर/add days'],['🔐','Password Generator','Utility','password','Random password बनाएं'],['▦','QR Code Generator','Utility','qr','Text/URL का QR'],['📏','Unit Converter','Utility','unit','Length, weight, temperature'],['🔤','Number to Words','Utility','numwords','Number को words में बदलें']];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>Number(n).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2});
function toast(s){let x=$('#toast');x.textContent=s;x.classList.add('showtoast');setTimeout(()=>x.classList.remove('showtoast'),2200)}
function dl(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function dltxt(s,n){dl(new Blob([s],{type:'text/plain'}),n)}
function fmt(n){if(!n)return'0 B';let u=['B','KB','MB','GB'],i=Math.floor(Math.log(n)/Math.log(1024));return(n/1024**i).toFixed(i?2:0)+' '+u[i]}
function img(file){return new Promise((res,rej)=>{let i=new Image;i.onload=()=>res(i);i.onerror=rej;i.src=URL.createObjectURL(file)})}
function blob(c,type,q=0.92){return new Promise(r=>c.toBlob(r,type,q))}
function pages(s,max){let a=new Set;String(s).split(',').forEach(x=>{if(x.includes('-')){let [p,q]=x.split('-').map(Number);if(p>q)[p,q]=[q,p];for(let i=p;i<=q;i++)if(i>=1&&i<=max)a.add(i)}else{let n=Number(x);if(n>=1&&n<=max)a.add(n)}});return[...a].sort((a,b)=>a-b)}
function box(id,title,body){return `<div class="head"><h2>${title}</h2><p class="muted">${body}</p></div>`}
function ui(id){switch(id){
case'jpgpdf':return box(id,'📄 JPG → PDF','एक या कई images')+`<div class="form"><div class="field full"><label>Images</label><input id="f" type="file" accept="image/*" multiple></div><div class="field"><label>Page size</label><select id="size"><option value="a4">A4</option><option value="letter">Letter</option><option value="original">Original</option></select></div><div class="field"><label>Orientation</label><select id="ori"><option>portrait</option><option>landscape</option></select></div><div class="field"><label>Margin</label><input id="margin" type="number" value="20"></div></div><div class="actions"><button class="btn" id="go">Convert</button></div><div id="r"></div>`;
case'pdfjpg':return box(id,'🖼️ PDF → JPG','All pages या selected pages')+`<div class="form"><div class="field full"><label>PDF</label><input id="f" type="file" accept="application/pdf"></div><div class="field"><label>Pages</label><select id="mode"><option value="all">All pages</option><option value="custom">Custom</option></select></div><div class="field"><label>Range</label><input id="range" placeholder="1-3,5" disabled></div><div class="field"><label>Quality</label><input id="q" type="range" min="40" max="100" value="90"></div></div><div class="actions"><button class="btn" id="go">Convert</button></div><div id="r"></div>`;
case'jpgpng':case'pngjpg':return box(id,id==='jpgpng'?'🔄 JPG → PNG':'🔄 PNG → JPG','Format conversion')+`<div class="form"><div class="field full"><label>Image</label><input id="f" type="file" accept="image/*"></div><div class="field"><label>Quality</label><input id="q" type="range" min="10" max="100" value="92"></div><div class="field"><label>JPG background</label><select id="bg"><option value="#fff">White</option><option value="#000">Black</option></select></div></div><div class="actions"><button class="btn" id="go">Convert</button></div><div id="r"></div>`;
case'compress':return box(id,'🗜️ Image Compressor','Quality और max width चुनें')+`<div class="form"><div class="field full"><label>Image</label><input id="f" type="file" accept="image/*"></div><div class="field"><label>Quality <span id="qv">80</span>%</label><input id="q" type="range" min="10" max="100" value="80"></div><div class="field"><label>Max width</label><input id="w" type="number" value="2000"></div><div class="field"><label>Output</label><select id="type"><option value="image/jpeg">JPG</option><option value="image/webp">WebP</option></select></div></div><div class="actions"><button class="btn" id="go">Compress</button></div><div id="r"></div>`;
case'resize':return box(id,'📐 Image Resizer','Dimensions बदलें')+`<div class="form"><div class="field full"><label>Image</label><input id="f" type="file" accept="image/*"></div><div class="field"><label>Width</label><input id="w" type="number"></div><div class="field"><label>Height</label><input id="h" type="number"></div><div class="field"><label>Output</label><select id="type"><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></div></div><div class="checks"><label><input id="keep" type="checkbox" checked> Keep aspect ratio</label></div><div class="actions"><button class="btn" id="go">Resize</button></div><div id="r"></div>`;
case'merge':return box(id,'📚 Merge PDF','Files के selected order में merge')+`<div class="field"><label>PDF files</label><input id="f" type="file" accept="application/pdf" multiple></div><div id="list" class="filelist"></div><div class="actions"><button class="btn" id="go">Merge PDF</button></div><div id="r"></div>`;
case'split':return box(id,'✂️ Split PDF','Pages जैसे 1-3,5')+`<div class="form"><div class="field full"><label>PDF</label><input id="f" type="file" accept="application/pdf"></div><div class="field"><label>Pages</label><input id="range" placeholder="1-3,5"></div></div><div class="actions"><button class="btn" id="go">Create PDF</button></div><div id="r"></div>`;
case'pdfcompress':return box(id,'🗜️ Compress PDF','Browser-only basic optimization')+`<div class="field"><label>PDF</label><input id="f" type="file" accept="application/pdf"></div><p class="small">हर PDF में size कम होना guaranteed नहीं है।</p><div class="actions"><button class="btn" id="go">Process PDF</button></div><div id="r"></div>`;
case'words':return box(id,'🔢 Word Counter','Live statistics')+`<div class="field"><textarea id="t" placeholder="Text paste करें..."></textarea></div><div id="r" class="result"></div><button class="btn download" id="dl">⬇️ Download TXT</button>`;
case'case':return box(id,'Aa Case Converter','Text case बदलें')+`<div class="field"><textarea id="t"></textarea></div><div class="actions"><button class="btn" data-c="upper">UPPERCASE</button><button class="btn secondary" data-c="lower">lowercase</button><button class="btn secondary" data-c="title">Title Case</button><button class="btn secondary" data-c="sentence">Sentence</button></div><div class="field"><textarea id="r"></textarea></div><button class="btn download" id="dl">⬇️ Download TXT</button>`;
case'percent':return calcUI('％ Percentage Calculator',['Value','Percentage'],['a','b'],(a,b)=>`Result: ${a*b/100}`);
case'emi':return calcUI('💰 EMI Calculator',['Loan amount','Annual interest %','Tenure months'],['a','b','c'],(p,r,n)=>{r/=1200;let e=r?p*r*(1+r)**n/((1+r)**n-1):p/n;return`Monthly EMI: ${money(e)}<br>Total interest: ${money(e*n-p)}<br>Total payment: ${money(e*n)}`});
case'gst':return calcUI('🧾 GST Calculator',['Amount','GST %'],['a','b'],(a,b)=>`GST: ${money(a*b/100)}<br>Total: ${money(a+a*b/100)}`);
case'discount':return calcUI('🏷️ Discount Calculator',['Original price','Discount %'],['a','b'],(a,b)=>`Discount: ${money(a*b/100)}<br>Final price: ${money(a-a*b/100)}`);
case'bmi':return calcUI('⚖️ BMI Calculator',['Weight kg','Height cm'],['a','b'],(a,b)=>{let x=a/(b/100)**2;return`BMI: ${x.toFixed(2)}<br>${x<18.5?'Underweight':x<25?'Normal':x<30?'Overweight':'Obesity'}`});
case'age':return box(id,'🎂 Age Calculator','DOB से age')+`<div class="form"><div class="field"><label>DOB</label><input id="a" type="date"></div><div class="field"><label>Calculate on</label><input id="b" type="date"></div></div><div class="actions"><button class="btn" id="go">Calculate</button></div><div id="r"></div>`;
case'date':return box(id,'📅 Date Calculator','Date difference और add days')+`<div class="form"><div class="field"><label>Start</label><input id="a" type="date"></div><div class="field"><label>End</label><input id="b" type="date"></div><div class="field"><label>Add days</label><input id="c" type="number" value="0"></div></div><div class="actions"><button class="btn" id="go">Calculate</button></div><div id="r"></div>`;
case'password':return box(id,'🔐 Password Generator','Length और character options')+`<div class="field"><label>Length <span id="lv">16</span></label><input id="len" type="range" min="4" max="128" value="16"></div><div class="checks"><label><input id="u" type="checkbox" checked> Uppercase</label><label><input id="l" type="checkbox" checked> Lowercase</label><label><input id="n" type="checkbox" checked> Numbers</label><label><input id="s" type="checkbox" checked> Symbols</label></div><input id="out" readonly><div class="actions"><button class="btn" id="go">Generate</button><button class="btn secondary" id="copy">Copy</button><button class="btn download" id="dl">⬇️ Download</button></div>`;
case'qr':return box(id,'▦ QR Code Generator','Text या URL')+`<div class="field"><textarea id="t"></textarea></div><div class="field"><label>Size</label><select id="size"><option>180</option><option selected>256</option><option>320</option></select></div><div class="actions"><button class="btn" id="go">Generate</button></div><div id="r"></div>`;
case'unit':return box(id,'📏 Unit Converter','Length, weight, temperature')+`<div class="form"><div class="field"><label>Category</label><select id="cat"><option>length</option><option>weight</option><option>temperature</option></select></div><div class="field"><label>Value</label><input id="v" type="number"></div><div class="field"><label>From</label><select id="from"></select></div><div class="field"><label>To</label><select id="to"></select></div></div><div class="actions"><button class="btn" id="go">Convert</button></div><div id="r"></div>`;
case'numwords':return box(id,'🔤 Number to Words','English या Hindi')+`<div class="form"><div class="field"><label>Number</label><input id="n" type="number" min="0" max="999999999999"></div><div class="field"><label>Language</label><select id="lang"><option value="en">English</option><option value="hi">Hindi</option></select></div></div><div class="actions"><button class="btn" id="go">Convert</button></div><div id="r"></div>`;
}}
function calcUI(title,labels,ids,fn){return box('',title,'Result के साथ download')+`<div class="form">${labels.map((x,i)=>`<div class="field"><label>${x}</label><input id="${ids[i]}" type="number"></div>`).join('')}</div><div class="actions"><button class="btn" id="go">Calculate</button></div><div id="r"></div>`}
function open(id){let t=tools.find(x=>x[3]===id);$('#content').innerHTML=ui(id);$('#modal').classList.add('show');bind(id)}
$('#grid').innerHTML=tools.map(t=>`<div class="card" data-id="${t[3]}"><div class="icon">${t[0]}</div><h3>${t[1]}</h3><p>${t[4]}</p></div>`).join('');
$('#grid').onclick=e=>{let c=e.target.closest('.card');if(c)open(c.dataset.id)};$('#close').onclick=()=>$('#modal').classList.remove('show');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('show')};$('#search').oninput=e=>document.querySelectorAll('.card').forEach(c=>c.style.display=c.textContent.toLowerCase().includes(e.target.value.toLowerCase())?'block':'none');
function result(id,text,download){$(id).innerHTML=`<div class="result"><b>✅ Result</b><p>${text}</p>${download?'<button class="btn download" id="rdl">⬇️ Download Result</button>':''}</div>`;if(download)$('#rdl').onclick=()=>dltxt(text.replace(/<br>/g,'\n'),'toolghar-result.txt')}
async function bind(id){
if(id==='jpgpdf'){$('#go').onclick=async()=>{let fs=[...$('#f').files];if(!fs.length)return toast('Images चुनें');try{let p=await PDFLib.PDFDocument.create(),m=+$('#margin').value||0;for(let f of fs){let bytes=await f.arrayBuffer(),im=f.type==='image/png'?await p.embedPng(bytes):await p.embedJpg(bytes),[w,h]=$('#size').value==='a4'?[595,842]:$('#size').value==='letter'?[612,792]:[im.width+m*2,im.height+m*2];if($('#ori').value==='landscape'&&$('#size').value!=='original')[w,h]=[h,w];let pg=p.addPage([w,h]),s=Math.min((w-2*m)/im.width,(h-2*m)/im.height);pg.drawImage(im,{x:(w-im.width*s)/2,y:(h-im.height*s)/2,width:im.width*s,height:im.height*s})}let b=new Blob([await p.save()],{type:'application/pdf'});$('#r').innerHTML='<div class="result">PDF ready<br><button class="btn download" id="d">⬇️ Download PDF</button></div>';$('#d').onclick=()=>dl(b,'toolghar-images.pdf')}catch(e){$('#r').innerHTML='<div class="result danger">'+esc(e.message)+'</div>'}}}
if(id==='pdfjpg'){$('#mode').onchange=()=>$('#range').disabled=$('#mode').value!=='custom';$('#go').onclick=async()=>{let f=$('#f').files[0];if(!f)return toast('PDF चुनें');try{let pdf=await pdfjsLib.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise,ps=$('#mode').value==='all'?Array.from({length:pdf.numPages},(_,i)=>i+1):pages($('#range').value,pdf.numPages),z=new JSZip();for(let n of ps){let p=await pdf.getPage(n),v=p.getViewport({scale:1.5}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;z.file(`page-${n}.jpg`,await blob(c,'image/jpeg',+$('#q').value/100))}let b=await z.generateAsync({type:'blob'});$('#r').innerHTML='<div class="result">'+ps.length+' JPG ready<br><button class="btn download" id="d">⬇️ Download ZIP</button></div>';$('#d').onclick=()=>dl(b,'toolghar-pdf-jpg.zip')}catch(e){$('#r').innerHTML='<div class="result danger">'+esc(e.message)+'</div>'}}}
if(['jpgpng','pngjpg'].includes(id))$('#go').onclick=async()=>{let f=$('#f').files[0];if(!f)return toast('Image चुनें');let i=await img(f),c=document.createElement('canvas');c.width=i.naturalWidth;c.height=i.naturalHeight;let x=c.getContext('2d');if(id==='pngjpg'){x.fillStyle=$('#bg').value;x.fillRect(0,0,c.width,c.height)}x.drawImage(i,0,0);let type=id==='jpgpng'?'image/png':'image/jpeg',b=await blob(c,type,+$('#q').value/100);$('#r').innerHTML=`<div class="result"><img class="preview" src="${URL.createObjectURL(b)}"><button class="btn download" id="d">⬇️ Download</button></div>`;$('#d').onclick=()=>dl(b,id==='jpgpng'?'converted.png':'converted.jpg')};
if(id==='compress'){$('#q').oninput=e=>$('#qv').textContent=e.target.value;$('#go').onclick=async()=>{let f=$('#f').files[0];if(!f)return toast('Image चुनें');let i=await img(f),s=Math.min(1,(+$('#w').value||i.naturalWidth)/i.naturalWidth),c=document.createElement('canvas');c.width=i.naturalWidth*s;c.height=i.naturalHeight*s;c.getContext('2d').drawImage(i,0,0,c.width,c.height);let type=$('#type').value,b=await blob(c,type,+$('#q').value/100);result('#r',`Before: ${fmt(f.size)}<br>After: ${fmt(b.size)}<br>Change: ${((1-b.size/f.size)*100).toFixed(1)}%`);$('#rdl').onclick=()=>dl(b,type==='image/webp'?'compressed.webp':'compressed.jpg')}}
if(id==='resize'){$('#f').onchange=async()=>{let i=await img($('#f').files[0]);$('#w').value=i.naturalWidth;$('#h').value=i.naturalHeight};$('#go').onclick=async()=>{let f=$('#f').files[0];if(!f)return toast('Image चुनें');let i=await img(f),w=+$('#w').value,h=+$('#h').value;if($('#keep').checked)h=Math.round(w*i.naturalHeight/i.naturalWidth);let c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(i,0,0,w,h);let type=$('#type').value,b=await blob(c,type,.92);$('#r').innerHTML='<div class="result"><img class="preview" src="'+URL.createObjectURL(b)+'"><button class="btn download" id="d">⬇️ Download</button></div>';$('#d').onclick=()=>dl(b,'resized.'+type.split('/')[1].replace('jpeg','jpg'))}}
if(id==='merge'){$('#f').onchange=()=>$('#list').innerHTML=[...$('#f').files].map((x,i)=>`<div class="fileitem">${i+1}. ${esc(x.name)}</div>`).join('');$('#go').onclick=async()=>{let fs=[...$('#f').files];if(fs.length<2)return toast('2+ PDFs चुनें');let o=await PDFLib.PDFDocument.create();for(let f of fs){let p=await PDFLib.PDFDocument.load(await f.arrayBuffer());(await o.copyPages(p,p.getPageIndices())).forEach(x=>o.addPage(x))}let b=new Blob([await o.save()],{type:'application/pdf'});$('#r').innerHTML='<div class="result">Merged PDF ready<br><button class="btn download" id="d">⬇️ Download</button></div>';$('#d').onclick=()=>dl(b,'merged.pdf')}}
if(id==='split')$('#go').onclick=async()=>{let f=$('#f').files[0],rs=$('#range').value;if(!f||!rs)return toast('PDF और pages दें');let s=await PDFLib.PDFDocument.load(await f.arrayBuffer()),ps=pages(rs,s.getPageCount()),o=await PDFLib.PDFDocument.create();(await o.copyPages(s,ps.map(x=>x-1))).forEach(x=>o.addPage(x));let b=new Blob([await o.save()],{type:'application/pdf'});$('#r').innerHTML='<div class="result">Split PDF ready<br><button class="btn download" id="d">⬇️ Download</button></div>';$('#d').onclick=()=>dl(b,'split.pdf')};
if(id==='pdfcompress')$('#go').onclick=async()=>{let f=$('#f').files[0];if(!f)return toast('PDF चुनें');let s=await PDFLib.PDFDocument.load(await f.arrayBuffer()),o=await PDFLib.PDFDocument.create();(await o.copyPages(s,s.getPageIndices())).forEach(x=>o.addPage(x));let b=new Blob([await o.save({useObjectStreams:true})],{type:'application/pdf'});$('#r').innerHTML=`<div class="result">Before: ${fmt(f.size)}<br>After: ${fmt(b.size)}<br><button class="btn download" id="d">⬇️ Download</button></div>`;$('#d').onclick=()=>dl(b,'processed.pdf')};
if(id==='words'){let up=()=>{let t=$('#t').value,w=t.trim()?t.trim().split(/\s+/).length:0;$('#r').innerHTML=`<div class="stats"><div class="stat">Words<b>${w}</b></div><div class="stat">Characters<b>${t.length}</b></div><div class="stat">Lines<b>${t?t.split(/\n/).length:0}</b></div></div>`};$('#t').oninput=up;up();$('#dl').onclick=()=>dltxt($('#t').value,'text.txt')}
if(id==='case'){$('[data-c="upper"]').onclick=()=>$('#r').value=$('#t').value.toUpperCase();$('[data-c="lower"]').onclick=()=>$('#r').value=$('#t').value.toLowerCase();$('[data-c="title"]').onclick=()=>$('#r').value=$('#t').value.toLowerCase().replace(/\b\w/g,x=>x.toUpperCase());$('[data-c="sentence"]').onclick=()=>$('#r').value=$('#t').value.toLowerCase().replace(/(^\s*\w|[.!?]\s+\w)/g,x=>x.toUpperCase());$('#dl').onclick=()=>dltxt($('#r').value,'case-result.txt')}
if(['percent','emi','gst','discount','bmi'].includes(id))$('#go').onclick=()=>{let a=+$('#a').value,b=+$('#b').value,c=+($('#c')?.value||0),txt;if(id==='percent')txt=`${a*b/100}`;if(id==='gst')txt=`GST: ${money(a*b/100)}<br>Total: ${money(a+a*b/100)}`;if(id==='discount')txt=`Discount: ${money(a*b/100)}<br>Final: ${money(a-a*b/100)}`;if(id==='bmi'){let x=a/(b/100)**2;txt=`BMI: ${x.toFixed(2)}`}if(id==='emi'){let r=b/1200,e=r?a*r*(1+r)**c/((1+r)**c-1):a/c;txt=`EMI: ${money(e)}<br>Interest: ${money(e*c-a)}<br>Total: ${money(e*c)}`}result('#r',txt,true)};
if(id==='age')$('#go').onclick=()=>{let d=new Date($('#a').value),x=new Date($('#b').value);if(isNaN(d)||isNaN(x))return toast('Dates चुनें');let y=x.getFullYear()-d.getFullYear(),m=x.getMonth()-d.getMonth(),day=x.getDate()-d.getDate();if(day<0){m--;day+=new Date(x.getFullYear(),x.getMonth(),0).getDate()}if(m<0){y--;m+=12}result('#r',`${y} years, ${m} months, ${day} days`,true)};
if(id==='date')$('#go').onclick=()=>{let a=new Date($('#a').value),b=new Date($('#b').value),n=+$('#c').value||0,x=new Date(a);x.setDate(x.getDate()+n);result('#r',`Difference: ${Math.round(Math.abs(b-a)/86400000)} days<br>Added date: ${x.toLocaleDateString('en-IN')}`,true)};
if(id==='password'){$('#len').oninput=e=>$('#lv').textContent=e.target.value;$('#go').onclick=()=>{let s='';if($('#u').checked)s+='ABCDEFGHIJKLMNOPQRSTUVWXYZ';if($('#l').checked)s+='abcdefghijklmnopqrstuvwxyz';if($('#n').checked)s+='0123456789';if($('#s').checked)s+='!@#$%^&*()_+-=';if(!s)return toast('Option चुनें');let a=new Uint32Array(+$('#len').value);crypto.getRandomValues(a);$('#out').value=[...a].map(x=>s[x%s.length]).join('')};$('#copy').onclick=()=>navigator.clipboard.writeText($('#out').value);$('#dl').onclick=()=>dltxt($('#out').value,'password.txt')}
if(id==='qr')$('#go').onclick=()=>{if(!$('#t').value)return toast('Text/URL लिखें');$('#r').innerHTML='<div class="result"><div id="qr" class="qr"></div></div>';new QRCode($('#qr'),{text:$('#t').value,width:+$('#size').value,height:+$('#size').value});setTimeout(()=>{$('#r .result').insertAdjacentHTML('beforeend','<button class="btn download" id="d">⬇️ Download PNG</button>');$('#d').onclick=async()=>{let c=$('#qr canvas');dl(await new Promise(r=>c.toBlob(r,'image/png')),'qr.png')}},200)};
if(id==='unit'){let data={length:{m:1,km:1000,cm:.01,mm:.001,ft:.3048,inch:.0254},weight:{kg:1,g:.001,lb:.453592,oz:.02835}};let fill=()=>{let c=$('#cat').value,o=c==='temperature'?['c','f','k']:Object.keys(data[c]);$('#from').innerHTML=o.map(x=>`<option>${x}</option>`).join('');$('#to').innerHTML=o.map(x=>`<option>${x}</option>`).join('')};fill();$('#cat').onchange=fill;$('#go').onclick=()=>{let c=$('#cat').value,v=+$('#v').value,a=$('#from').value,b=$('#to').value,r;if(c==='temperature'){let z=a==='c'?v:a==='f'?(v-32)*5/9:v-273.15;r=b==='c'?z:b==='f'?z*9/5+32:z+273.15}else r=v*data[c][a]/data[c][b];result('#r',String(r),true)}}
if(id==='numwords'){$('#go').onclick=()=>{let n=Math.floor(+$('#n').value||0);let small=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'],t=n<20?small[n]:n<100?['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'][Math.floor(n/10)]+(n%10?' '+small[n%10]:''):n<1000?small[Math.floor(n/100)]+' hundred'+(n%100?' '+small[n%100]:''):String(n);result('#r',t,true)}}
}
